// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU63NqF3R6ZnGRyco-ww0g3MWZXofCFHc',
    appId: '1:585313610705:web:e3355b39bde2481ea58ef0',
    messagingSenderId: '585313610705',
    projectId: 'chatlowers',
    authDomain: 'chatlowers.firebaseapp.com',
    databaseURL: 'https://chatlowers-default-rtdb.firebaseio.com',
    storageBucket: 'chatlowers.appspot.com',
    measurementId: 'G-Y5MW7JD56B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf_VMl-XqoSElzLPSnaDQC__rl-N0GhhY',
    appId: '1:585313610705:android:63ed6d2bd0879078a58ef0',
    messagingSenderId: '585313610705',
    projectId: 'chatlowers',
    databaseURL: 'https://chatlowers-default-rtdb.firebaseio.com',
    storageBucket: 'chatlowers.appspot.com',
  );
}
